#!/bin/bash

# move to working directory
cd $( dirname "${BASH_SOURCE[0]}" )
start_dir=$(pwd)

# reset db
echo "creating database..."

if [ ! -f tests/credentials.local.bash ]; then
  cd tests
  ../_resources/SQL/create_db_user.sql.bash -test
  cd -
fi

source tests/credentials.local.bash
source _resources/SQL/ddl.sql.inc.bash
echo "...database created"

# PHP Unit tests
cd $start_dir
./vendor/bin/phpunit --bootstrap tests/tests.loader.inc.php --testdox tests
